apiVersion: v1
kind: ConfigMap
metadata:
  name: bankops-config
  namespace: bankops
  labels:
    app.kubernetes.io/name: bankops-ai
    app.kubernetes.io/part-of: banking-platform
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  QDRANT_HOST: "qdrant.bankops.svc.cluster.local"
  QDRANT_PORT: "6333"
  OLLAMA_HOST: "http://ollama.bankops.svc.cluster.local:11434"
  OLLAMA_MODEL: "llama3.2"
  EMBEDDING_MODEL: "nomic-embed-text"
  PROMETHEUS_METRICS_ENABLED: "true"
