apiVersion: v1
kind: Secret
metadata:
  name: bankops-secrets
  namespace: bankops
  labels:
    app.kubernetes.io/name: bankops-ai
type: Opaque
stringData:
  JWT_SECRET: "change-this-in-production-vault-injected-jwt-secret-key-32-chars-min"
  DATABASE_URL: "postgresql+asyncpg://bankops_user:vault_generated_secure_pw@postgres.bankops.svc.cluster.local:5432/bankops"
